- removed env: {es2021: true} from .eslintrc.js
after storybook files were added, I could not run 'npm run lint'
Error:
> npm run lint
> create-react-app-with-typescript-template@0.1.0 lint /Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template
> eslint 'src/**/*.{js,jsx,ts,tsx}'

Error: .eslintrc.js:
        Environment key "es2021" is unknown

    at Object.keys.forEach.id (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/shared/config-validator.js:169:19)
    at Array.forEach (<anonymous>)
    at validateEnvironment (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/shared/config-validator.js:163:30)
    at validateConfigArray (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/shared/config-validator.js:334:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesRecursive (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/ruanbeukes/repos/React-storybook-template/create-react-app-with-typescript-template/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:49)
    at iterateFiles.next (<anonymous>)